#Full acquire
python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --qos-acquisition-interval=1000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="acquire" --test-list=1Values@2Values@3Values@4Values@5Values@6Values@7Values@8Values@1Values-id@2Values-id@3Values-id@4Values-id@5Values-id@6Values-id@7Values-id@8Values-id@1Values-time@2Values-time@3Values-time@4Values-time@5Values-time@6Values-time@7Values-time@1Values-id-time@2Values-id-time@3Values-id-time@4Values-id-time@5Values-id-time@6Values-id-time@7Values-id@8Values-id@01ValuesWith1ADC@01ValuesWith2ADC@1ValuesWith1ADC@1ValuesWith2ADC@02ValuesWith2ADC@02ValuesWith3ADC@2ValuesWith2ADC@2ValuesWith3ADC@03ValuesWith3ADC@3ValuesWith3ADC@3ValuesWith3ADCPlus2


#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-max-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --qos-acquisition-interval=1000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="full100" --test-list=6Values-id-time@7Values-time@8Values-id

#@1Values-id@2Values-id@3Values-id@4Values-id@5Values-id@6Values-id@1Values-time@2Values-time@3Values-time@1Values-id-time@2Values-id-time@3Values-id-time@4Values

#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --qos-acquisition-interval=1000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in-list="","acquire" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="acquire/thin" --test-list="1Values-ignoreAll"

#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --qos-acquisition-interval=1000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="acquire/ADC" --test-list=2ndADC:2Values,1Values-time@3rdADC:3Values,2Values-time
