#Whole Project then stop
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators-list=False,True --measurement-dir="Project/Stop" --test-list="1Values"@"2Values"@"3Values"@"1Values-id"@"2Values-id"@"3Values-id"@"1Values-time"@"2Values-time"@"3Values-time"@"1Values-id-time"@"2Values-id-time"@"3Values-id-time"@"1Values-time-id"@"time-1Values-id"

#Project Ignore
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in-list="project","project" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators-list=False,True --measurement-dir="Project/Ignore" --test-list="1Values-id-time-ignoreAll"@"2Values-id-time-ignoreAll"@"3Values-id-time-ignoreAll"

#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in-list="project","project" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators-list=False,True --measurements-multi-acquire=2 --measurement-dir="Project/Ignore2" --test-list="1Values-id-time-ignoreAll"@"2Values-id-time-ignoreAll"@"3Values-id-time-ignoreAll"

#Project/Stop2ndTuple
python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators-list=False,False,True,True --measurements-multi-acquire-list=2,1,2,1 --measurement-dir="Project/Stop2ndTuple" --test-list="1Values"@"2Values"@"3Values"@"1Values-id"@"2Values-id"@"3Values-id"@"1Values-time"@"2Values-time"@"3Values-time"@"1Values-id-time"@"2Values-id-time"@"3Values-id-time"@"1Values-time-id"@"time-1Values-id"

#Project/Stop3rdhTuple
python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=False --measurements-multi-acquire-list=3,2 --measurement-dir="Project/Stop3ndTuple" --test-list="1Values"@"2Values"@"3Values"@"1Values-id"@"2Values-id"@"3Values-id"@"1Values-time"@"2Values-time"@"3Values-time"@"1Values-id-time"@"2Values-id-time"@"3Values-id-time"@"1Values-time-id"@"time-1Values-id"

#Project/Stop4thTuple
python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="trayAlldeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=False --measurements-multi-acquire-list=4,3 --measurement-dir="Project/Stop4thTuple" --test-list="1Values"@"2Values"@"3Values"@"1Values-id"@"2Values-id"@"3Values-id"@"1Values-time"@"2Values-time"@"3Values-time"@"1Values-id-time"@"2Values-id-time"@"3Values-id-time"@"1Values-time-id"@"time-1Values-id"

#Full no Stop
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators="" --measurements-thin-operators="" --remove-unrequired-operators-list=False,True --measurement-dir="Project/Full" --test-list="1Values"@"2Values"@"3Values"@"1Values-id"@"2Values-id"@"3Values-id"@"1Values-time"@"2Values-time"@"3Values-time"@"1Values-id-time"@"2Values-id-time"@"3Values-id-time"

