#Tray out acquire card 1
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="Deliver","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_Out1" --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time@01Values@02Values@01Values-id@03Values@02Values-id@01Values-time@04Values@03Values-id@02Values-time@01Values-id-time@05Values@04Values-id@03Values-time@02Values-id-time@06Values@05Values-id@04Values-time@03Values-id-time@07Values@06Values-id@05Values-time@04Values-id-time@08Values@07Values-id@06Values-time@05Values-id-time@09Values@08Values-id@07Values-time@06Values-id-time

python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="Deliver","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_Out2" --measurements-multi-acquire-list=2,2 --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time@01Values@02Values@01Values-id@03Values@02Values-id@01Values-time@04Values@03Values-id@02Values-time@01Values-id-time@05Values@04Values-id@03Values-time@02Values-id-time@06Values@05Values-id@04Values-time@03Values-id-time@07Values@06Values-id@05Values-time@04Values-id-time@08Values@07Values-id@06Values-time@05Values-id-time@09Values@08Values-id@07Values-time@06Values-id-time

#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="Deliver","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_Out3" --measurements-multi-acquire-list=3,3 --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time@01Values@02Values@01Values-id@03Values@02Values-id@01Values-time@04Values@03Values-id@02Values-time@01Values-id-time@05Values@04Values-id@03Values-time@02Values-id-time@06Values@05Values-id@04Values-time@03Values-id-time@07Values@06Values-id@05Values-time@04Values-id-time@08Values@07Values-id@06Values-time@05Values-id-time@09Values@08Values-id@07Values-time@06Values-id-time

#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="Deliver","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_Out4" --measurements-multi-acquire-list=4,4 --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time@01Values@02Values@01Values-id@03Values@02Values-id@01Values-time@04Values@03Values-id@02Values-time@01Values-id-time@05Values@04Values-id@03Values-time@02Values-id-time@06Values@05Values-id@04Values-time@03Values-id-time@07Values@06Values-id@05Values-time@04Values-id-time@08Values@07Values-id@06Values-time@05Values-id-time@09Values@08Values-id@07Values-time@06Values-id-time

#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="Deliver","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_Out5" --measurements-multi-acquire-list=5,5 --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time@01Values@02Values@01Values-id@03Values@02Values-id@01Values-time@04Values@03Values-id@02Values-time@01Values-id-time@05Values@04Values-id@03Values-time@02Values-id-time@06Values@05Values-id@04Values-time@03Values-id-time@07Values@06Values-id@05Values-time@04Values-id-time@08Values@07Values-id@06Values-time@05Values-id-time@09Values@08Values-id@07Values-time@06Values-id-time

#Tray in acquire card 1
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverAll","TrayAllDeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_localIn1" --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time@01Values@02Values@01Values-id@03Values@02Values-id@01Values-time@04Values@03Values-id@02Values-time@01Values-id-time@05Values@04Values-id@03Values-time@02Values-id-time@06Values@05Values-id@04Values-time@03Values-id-time@07Values@06Values-id@05Values-time@04Values-id-time@08Values@07Values-id@06Values-time@05Values-id-time@09Values@08Values-id@07Values-time@06Values-id-time

#Tray in acquire card 2
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverAll","TrayAllDeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurements-multi-acquire-list=2,2 --measurement-dir="tray_localIn2" --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time

#Tray in acquire card 3
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverAll","TrayAllDeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurements-multi-acquire-list=3,3 --measurement-dir="tray_localIn3" --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time

#Tray in acquire card 4
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverAll","TrayAllDeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurements-multi-acquire-list=4,4 --measurement-dir="tray_localIn4" --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time

#Tray in acquire card 5
#python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=101 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_TRAY_WRITE_TIMES_EXPREMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverAll","TrayAllDeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurements-multi-acquire-list=5,5 --measurement-dir="tray_localIn5" --test-list=1Values@2Values@1Values-id@3Values@2Values-id@1Values-time@4Values@3Values-id@2Values-time@1Values-id-time@5Values@4Values-id@3Values-time@2Values-id-time@6Values@5Values-id@4Values-time@3Values-id-time@7Values@6Values-id@5Values-time@4Values-id-time@8Values@7Values-id@6Values-time@5Values-id-time@9Values@8Values-id@7Values-time@6Values-id-time

