#tray_localOutFull 1
python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverInOnly","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_localOutFull" --test-list="3Values-id-time":"3Values-id-time","3Values-id-time"

python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverInOnly","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_localOutFull" --measurements-multi-acquire-list=2,2
--test-list="3Values-id-time":"3Values-id-time","3Values-id-time"

python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverInOnly","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_localOutFull" --measurements-multi-acquire-list=3,3
--test-list="3Values-id-time":"3Values-id-time","3Values-id-time"

python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverInOnly","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_localOutFull" --measurements-multi-acquire-list=4,4 --test-list="3Values-id-time":"3Values-id-time","3Values-id-time"

python scripts/batch/DoAvroraSim.py --compile-query=True --compile-nesc=True --nesc-led-debug=True --simulation-Duration=100 --push-projection-down=True --measurements-active-agenda-loops=5 --schema-file=input/measurements/1Site-1Source-schemas.xml --operator-metadata-file="input/cost-parameters-mininterval1000.xml" --qos-acquisition-interval=5000 --nesc-yellow-experiment=GET_PRODUCER_TIMES_EXPERIMENT --query-dir="input/measurements" --ouput-root="c:/measurements" --qos-buffering-factor=1 --measurements-ignore-in="" --measurements-remove-operators-list="DeliverInOnly","DeliverAll" --measurements-thin-operators="" --remove-unrequired-operators=True --measurement-dir="tray_localOutFull" --measurements-multi-acquire-list=4,4
--test-list="3Values-id-time":"3Values-id-time","3Values-id-time"
